In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([[1,0,1,0], [1,0,1,1], [0,1,0,1]])
y = np.array([[1],[1],[0]])

In [3]:
# Activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [4]:
def derivativeSigmoid(x):
  return x*(1-x)

In [27]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1

epochs = 40000
alpha = 0.01  # learning_rate

In [28]:
# Weights and Bias Initialization
weightHidden = np.random.uniform(size=(input_neurons, hidden_neurons))
biasHidden = np.random.uniform(size=(1, hidden_neurons))
weightOutput = np.random.uniform(size=(hidden_neurons, output_neurons))
biasOutput = np.random.uniform(size=(1, output_neurons))

In [29]:
for i in range(epochs):
  # Feedforward
  z1 = np.dot(X, weightHidden) + biasHidden
  hidden_layer = sigmoid(z1)

  z2 = np.dot(hidden_layer, weightOutput) + biasOutput
  output_layer = sigmoid(z2)

  # Backpropagation
  error_output_layer = y - output_layer
  slope_output_layer = derivativeSigmoid(output_layer)
  delta_output = error_output_layer * slope_output_layer

  error_hidden_layer = np.dot(delta_output, weightOutput.T)
  slope_hidden_layer = derivativeSigmoid(hidden_layer)
  delta_hidden = error_hidden_layer * slope_hidden_layer

  weightOutput += np.dot(hidden_layer.T, delta_output) * alpha
  weightHidden += np.dot(X.T, delta_hidden) * alpha
  biasOutput += np.sum(delta_output, axis=0, keepdims=True) * alpha
  biasHidden += np.sum(delta_hidden, axis=0, keepdims=True) * alpha


In [30]:
print(output_layer)

[[0.97773265]
 [0.96892354]
 [0.03931746]]


In [31]:
np.round(output_layer)

array([[1.],
       [1.],
       [0.]])

In [32]:
y

array([[1],
       [1],
       [0]])

In [33]:
error = y - output_layer
print(error)

[[ 0.02226735]
 [ 0.03107646]
 [-0.03931746]]
